skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
altscore_solana = "9muywZZ7xaLb9cLVrWd9iLnUe6asSMndQ2Z4NhZwXuzg"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
